version: 2
jobs:
  build-ruby-2.3:
    working_directory: ~/active_campaign/ruby-2.3
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: active_campaign_rb-ruby-2_3-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: active_campaign_rb-ruby-2_3-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: bundle exec rake

  build-ruby-2.4:
    working_directory: ~/active_campaign/ruby-2.4
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: active_campaign_rb-ruby-2_4-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: active_campaign_rb-ruby-2_4-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: bundle exec rake

  build-ruby-2.5:
    working_directory: ~/active_campaign/ruby-2.5
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: active_campaign_rb-ruby-2_5-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: active_campaign_rb-ruby-2_5-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: bundle exec rake
