version: 2
defaults: &defaults
  working_directory: ~/active_campaign

test_steps: &test_steps
  - checkout

  # Restore Cached Dependencies
  - restore-cache:
      keys:
      - active_campaign_rb-{{ .Environment.CIRCLE_JOB }}-{{ checksum "active_campaign.gemspec" }}
      # fallback to using the latest cache if no exact match is found
      - active_campaign_rb-ruby-{{ .Environment.CIRCLE_JOB }}-

  # Bundle install dependencies
  - run: bundle install --path vendor/bundle

  # Cache Dependencies
  - save_cache:
      paths:
        - ./vendor/bundle
      key: active_campaign_rb-{{ .Environment.CIRCLE_JOB }}-{{ checksum "active_campaign.gemspec" }}

  - run:
      name: Run tests
      command: |
        mkdir /tmp/test-results
        TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

        bundle exec rspec --format progress \
                        --format RspecJunitFormatter \
                        --out /tmp/test-results/rspec.xml \
                        --format progress \
                        $TEST_FILES

  # collect reports
  - store_test_results:
      path: /tmp/test-results
  - store_artifacts:
      path: /tmp/test-results
      destination: test-results

jobs:
  build-ruby-2.3:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.3
    steps: *test_steps


  build-ruby-2.4:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4
    steps: *test_steps

  build-ruby-2.5:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
    steps: *test_steps

workflows:
  version: 2
  tests:
    jobs:
      - build-ruby-2.3
      - build-ruby-2.4
      - build-ruby-2.5
