version: 2
defaults: &defaults
  working_directory: ~/active_campaign

test_steps: &test_steps
  - checkout
  - attach_workspace:
      at: ~/active_campaign/tmp

  # Restore Cached Dependencies
  - restore-cache:
      keys:
      - active_campaign_rb-{{ .Environment.CIRCLE_JOB }}-{{ checksum "active_campaign.gemspec" }}
      # fallback to using the latest cache if no exact match is found
      - active_campaign_rb-ruby-{{ .Environment.CIRCLE_JOB }}-

  # Bundle install dependencies
  - run: gem uninstall bundler
  - run: gem install bundler -v 2.0.1
  - run: bundle install --path vendor/bundle

  # Cache Dependencies
  - save_cache:
      paths:
        - ./vendor/bundle
      key: active_campaign_rb-{{ .Environment.CIRCLE_JOB }}-{{ checksum "active_campaign.gemspec" }}

  - run:
      name: Run tests
      command: |
        mkdir ./tmp/test-results
        TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

        bundle exec rspec --format progress \
                        --format RspecJunitFormatter \
                        --out /tmp/test-results/rspec.xml \
                        --format progress \
                        $TEST_FILES
        ./tmp/cc-test-reporter format-coverage -t simplecov -o "tmp/codeclimate.$CIRCLE_JOB.json" "coverage/$CIRCLE_JOB/.resultset.json"

  - persist_to_workspace:
      root: tmp
      paths:
        - codeclimate.*.json

  # collect reports
  - store_test_results:
      path: /tmp/test-results
  - store_artifacts:
      path: /tmp/test-results
      destination: test-results

jobs:
  download_code_climate_reporter:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
    steps:
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

  build-ruby-2.3:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.3
    steps: *test_steps


  build-ruby-2.4:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4
    steps: *test_steps

  build-ruby-2.5:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
    steps: *test_steps

  upload-coverage-to-code-climate:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
    environment:
      - CC_TEST_REPORTER_ID: a877f9b044604a7f2f157be28ec0f5ec7f6a54e03bddf68e0c07f5a4b5937584
    steps:
      - attach_workspace:
          at: ~/active_campaign/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 3 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json

workflows:
  version: 2
  tests:
    jobs:
      - download_code_climate_reporter
      - build-ruby-2.3:
          requires:
            - download_code_climate_reporter
      - build-ruby-2.4:
          requires:
            - download_code_climate_reporter
      - build-ruby-2.5:
          requires:
            - download_code_climate_reporter
      - upload-coverage-to-code-climate:
          requires:
            - build-ruby-2.3
            - build-ruby-2.4
            - build-ruby-2.5
